version: '3.8'

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=chorkn8n.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://chorkn8n.com/
      - N8N_EDITOR_BASE_URL=https://chorkn8n.com/
      - GENERIC_TIMEZONE=America/New_York
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - EXECUTIONS_PROCESS=main
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - NODES_INCLUDE=n8n-nodes-base.executeCommand
    volumes:
      - n8n_data:/home/n8n/.n8n

volumes:
  n8n_data:
